# ---------- PostgreSQL Database ----------
services:
  db:
    image: postgres:16-alpine
    container_name: dadjokes-db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: dadjokes
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_DB: dadjokes
    secrets:
      - postgres_password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dadjokes"]
      interval: 5s
      timeout: 5s
      retries: 5
  # ---------- Express API ----------
  api:
    build:
      context: ./api
      target: dev
    container_name: dadjokes-api
    ports:
      - 3000:3000
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: dadjokes
      DB_PASSWORD_FILE: /run/secrets/postgres_password
      DB_NAME: dadjokes
      RESEND_API_KEY_FILE: /run/secrets/resend_APIKey
    secrets:
        - postgres_password
        - resend_APIKey
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    develop:
      watch:
        - path: ./api/src 
          target: /app/src
          action: sync
        - path: ./api/package.json
          target: /app/package.json
          action: rebuild
        - path: ./api/package-lock.json
          target: /app/package-lock.json
          action: rebuild

  # ---------- React Frontend (served by nginx) ----------
  frontend:
    build:
      context: ./frontend
      target: dev
    container_name: dadjokes-frontend
    ports:
      # - "8080:80"
      - 8080:5173
    secrets:
        - postgres_password
    depends_on:
      - api
    restart: unless-stopped
#   command: ["npm", "run", "dev"]

    develop:
      watch:
        - path: ./frontend/src 
          target: /app/src
          action: sync
        - path: ./frontend/index.html 
          target: /app/index.html
          action: sync
        - path: ./frontend/nginx.conf
          target: /etc/nginx/conf.d/default.conf
          action: sync+restart
        - path: ./frontend/package.json
          target: /app/package.json
          action: rebuild
        - path: ./frontend/package-lock.json
          target: /app/package-lock.json
          action: rebuild
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD_FILE: /run/secrets/pgadmin_password
    secrets:
      - pgadmin_password
    ports:
      - "5050:80"
    depends_on:
      - db
      

secrets:
  postgres_password:
    file: ./secrets/POSTGRES_PASSWORD.txt
  pgadmin_password:
    file: ./secrets/PGADMIN_PASSWORD.txt
  pgadmin_email:
    file: ./secrets/PGADMIN_EMAIL.txt
  resend_APIKey:
    file: ./secrets/RESEND_APIKEY.txt

volumes:
  pgdata:
